language: objective-c
osx_image: xcode8
script:
  - cd Example
  - pod install
  - xcodebuild -scheme WRClock -workspace WRClock.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.0' build
